import 'server-only'
import JSZip from 'jszip'
import type { GeneratedLesson } from '@/types'

export function buildReadme(
  courseTitle: string,
  courseDescription: string,
  lessons: GeneratedLesson[],
): string {
  const safeTitle = (courseTitle ?? '').slice(0, 200)
  const safeDescription = (courseDescription ?? '').slice(0, 1000)

  const toc = lessons
    .map(l => `${l.lessonNumber}. **${l.title}** — ${l.filename}`)
    .join('\n')

  return `# ${safeTitle}

${safeDescription}

## Lessons

${toc}

---

*Generated by substack2eec*
`
}

export async function buildZip(
  lessons: GeneratedLesson[],
  courseTitle: string,
  courseDescription: string,
): Promise<ArrayBuffer> {
  const zip = new JSZip()

  zip.file('README.md', buildReadme(courseTitle, courseDescription, lessons))

  for (const lesson of lessons) {
    zip.file(lesson.filename, lesson.markdownBody)
  }

  return zip.generateAsync({ type: 'arraybuffer' })
}
